### ISSUE TITLE
Mannpower is a little buggy

### ISSUE THREAD

**Issue by RexenSquared** [Wiethoofd/WietHUD#3]
One the supernova power up thingy, its meter is misleading as it gets full before its full charge.
Two when spectating someone who has a power up the power up's icon shows a missing texture

**Comment by Wiethoofd** [comment]
The power up icons is because of the '[higher quality item images](http://www.teamfortress.tv/25428/higher-quality-item-images-in-inventory-loadouts)' which apparently aren't available for the power ups.

I think I know the issue for the chargebar, since it's using the original bar hud element, but only reduces the size of the box to fit the label, but not the actual bar itself.

**Comment by RexenSquared** [comment]
So about the higher quality item thing. Does that mean you have to make "hq" versions of the powerup icons? Or is it just as simple as fixing a typo?

**Comment by Wiethoofd** [comment]
For the HQ images there is nothing much I can do besides disabling the higher quality images for all the inspect panels.
