### ISSUE TITLE
Some people seem to be having issue seeding there paint

### ISSUE THREAD

**Issue by RexenSquared** [Wiethoofd/WietHUD#5]
Here's a thread from reddit
https://www.reddit.com/r/tf2/comments/7a35ce/i_love_how_wiethud_allows_setting_the_seed_for_a/dp6ryc9/

**Comment by Wiethoofd** [comment]
I also [left a response](https://www.reddit.com/r/tf2/comments/7a35ce/i_love_how_wiethud_allows_setting_the_seed_for_a/dp7nywa/) explaining my thought process on the randomize seed field + button when redeeming war paints.

Turns out this was never a thing or was actually disabled by valve.
I did not properly test this because I lacked the actual War Paints to redeem!
